### PR TITLE
Adding gitgraft and adding pycharm files to gitignore

### PR DESCRIPTION
**Pull request by bmedx**

### CODE REVIEW

**Comment by feanil** [comment]
Is the plan to start using this with pipelines?

**Comment by bmedx** [comment]
@feanil No, it would not generally be good for that. @doctoryes suggested this was the place for it, but I'm happy to discuss alternatives if you think otherwise.

**Comment by doctoryes** [comment]
@feanil I advised @bmedx to put this script here. It's being used in the modulestore extraction project - and it needed to go in some repo to avoid making yet another repo. Can you suggest a more appropriate place?

**Comment by doctoryes** [comment]
@feanil ping - is there another place you'd suggest?

**Comment by feanil** [comment]
https://github.com/edx/edx-tools or https://github.com/edx/repo-tools seem like reasonable places perhaps?

**Comment by macdiesel** [comment]
@bmedx @doctoryes Can this PR be closed?

**Comment by doctoryes** [comment]
@bmedx I looked at the two repos - seems like repo-tools is the more appropriate of the two?

**Comment by bmedx** [comment]
Fair enough, I shall move it there!

**Pull request closed without merging**
