### PR TITLE
Install PyGithub from PyPI

### PR DESCRIPTION
**Pull request by rlucioni**
The change we contributed was released with 1.27.1.

@edx/pipeline-team

### CODE REVIEW

**Comment by rlucioni** [comment]
I'm not authorized to merge this PR. It would be great if someone reviewing could do it for me or give me write access.

**Review by macdiesel — APPROVED** [review]

**Comment by macdiesel** [comment]
@rlucioni I will merge it.

**Comment by rlucioni** [comment]
@macdiesel thanks!

**Comment by doctoryes** [comment]
:awesomesauce:

**Pull request merged**
