### PR TITLE
[FAL-2409] Update PyGithub dependency for Lilac

### PR DESCRIPTION
**Pull request by 0x29a**
This will fix the errors when trying to install PyGitHub using newer versions of setuptools that don't support use_2to3.

Command that I've used to generate `base.txt`:
```
pip-compile -v --no-emit-trusted-host --no-emit-index-url --rebuild --upgrade-package PyGithub -o requirements/base.txt requirements/base.in
```

Note: pip-compile reordered some dependencies, but didn't upgrade anything except PyGithub.

Same fix for `master`: https://github.com/edx/tubular/pull/532

**Testing instructions**:

1. Check that package can be installed:
    ```bash
    pip install -e .
    ```
2. Run tests:
    ```
    tox -- -n0
    ```

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @0x29a! I've created [OSPR-6040](https://openedx.atlassian.net/browse/OSPR-6040) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@0x29a Thank you for your contribution. Please let me know once it is ready for our review.

**Review by lgp171188 — APPROVED** [review]
:+1: 
- [x] I tested this and verified that only the `PyGitHub` library is updated to a newer version with the fix for the issue. All the other changes only alphabetically re-order the existing libraries or remove those not needed any more.
- [x] I read through the code
- [x] ~~I checked for accessibility issues~~ NA
- [x] ~~Includes documentation~~ NA

**Comment by lgp171188** [comment]
> Thank you for your contribution. Please let me know once it is ready for our review.

@natabene, this PR is ready for edX review. @nedbat, this is the Lilac backport PR corresponding to https://github.com/edx/tubular/pull/532.

The CI checks are failing due to an unrelated reason - the pinned version of cryptography no longer supporting Python 3.5.

**Review by nadeemshahzad — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@0x29a 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/tubular&entry.867055334=https://github.com/edx/tubular/pull/531&entry.1484655318=https://github.com/0x29a&entry.752974735=2021-09-13+11:13&entry.1917517419=2021-09-15+11:27&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
