### PR TITLE
Add scripts/tests to validate edp and restrict to stage.

### PR DESCRIPTION
**Pull request by doctoryes**
@edx/pipeline-team Please review.

https://openedx.atlassian.net/browse/TE-1366

### CODE REVIEW

**Comment by macdiesel** [comment]
@doctoryes why not just take restrict_to_stage and validate to the ec2 module and just have the scripts call them from the ec2 module? I think it would make the code a bit cleaner and you are already testing it in the test_ec2 module anyway.

**Comment by doctoryes** [comment]
@macdiesel Given the limitations in being able to test the scripts, your proposal makes sense. This restriction will end up pushing all script functionality into core python code, which I guess isn't a bad thing - the scripting layer could fall away without losing most of the functionality it implements. Bottom line: I'll do so.

**Comment by doctoryes** [comment]
@macdiesel Done. Ready for re-review.

**Comment by macdiesel** [comment]
👍 🚢 🇮🇹

**Pull request merged**
