### PR TITLE
moved util.py location

### PR DESCRIPTION
**Pull request by macdiesel**
@feanil @doctoryes Some code cleanup in prep for retry code.

### CODE REVIEW

**Comment by feanil** [comment]
👍

**Comment by doctoryes** [comment]
Nit: `util.py` has two lines in it, which could be moved to `__init__.py`. I'm inclined to remove that file for now. But not a blocker.

**Comment by doctoryes** [comment]
👍 A nit - but your call.

**Comment by macdiesel** [comment]
@doctoryes good idea, makes the code cleaner. I'm going to make the change and merge.

**Pull request merged**
