### PR TITLE
FAL-2409 Update PyGithub dependency

### PR DESCRIPTION
**Pull request by samuelallan72**
[FAL-2409](https://tasks.opencraft.com/browse/FAL-2409) | [OSPR-6029](https://openedx.atlassian.net/browse/OSPR-6029)

1.43.8 had use_2to3 defined in setup(),
which is is removed in recent setuptools versions.

Note: I used `make upgrade` to re-compile the requirements files.  This seems to have done some minor unrelated changes (reordering the file, some patch version updates).  Please check.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @swalladge! I've created [OSPR-6029](https://openedx.atlassian.net/browse/OSPR-6029) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by lgp171188** [comment]
@nedbat, FYI. This is breaking the installation of the user_retirement service, which uses this repository. We will likely have to backport this fix to the Lilac release branch (and older release branches, if it makes sense to).

**Comment by lgp171188** [comment]
@arbrandes, FYI, as we will have to backport this fix to the Lilac branch.

**Comment by nedbat** [comment]
I would be reluctant to cherry-pick a change that updated many dependencies.  For Lilac, a more targeted change that only updated the needed dependency might be better.  But maybe other release managers have a different approach.

**Comment by natabene** [comment]
@swalladge Thank you for your contribution. Is this ready for our SRE review?

**Comment by samuelallan72** [comment]
@lgp171188 @nedbat @arbrandes as far as I can work out, edx/configuration uses the master branch of this by default for all releases, so no backport necessary?  Although I do see lilac release tags have been added here.

The version is defined [here in configuration](https://github.com/edx/configuration/blob/b185437d1210f440ea9bc5d03c1590f443cc7cf4/playbooks/roles/user_retirement_pipeline/defaults/main.yml#L34), and I can't find anywhere that overrides it (not conditionally elsewhere in configuration, not in the devstack, nor our ocim).

**Comment by samuelallan72** [comment]
@natabene not yet sorry; we're still reviewing this internally. :)

**Comment by samuelallan72** [comment]
superceded by https://github.com/open-craft/tubular/pull/1

**Comment by lgp171188** [comment]
> I would be reluctant to cherry-pick a change that updated many dependencies. For Lilac, a more targeted change that only updated the needed dependency might be better. But maybe other release managers have a different approach.

@nedbat, this PR is superseded by https://github.com/edx/tubular/pull/532, which only updates the `PyGitHub` version and https://github.com/edx/tubular/pull/531 is a similar backport for Lilac.

The CI checks on the Lilac backport PR are failing due to an unrelated reason - the pinned version of `cryptography` no longer supporting Python 3.5.

CC @0x29a

**Comment by openedx-webhooks** [comment]
@swalladge Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/tubular&entry.867055334=https://github.com/edx/tubular/pull/529&entry.1484655318=https://github.com/swalladge&entry.752974735=2021-09-08+01:13&entry.1917517419=2021-09-09+22:28&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
