### PR TITLE
FC-0001: Remove EdxRestApiClient usage in tubular

### PR DESCRIPTION
**Pull request by ruzniaievdm**
JIRA: [DEPR-138](https://openedx.atlassian.net/browse/DEPR-138)
https://github.com/openedx/public-engineering/issues/38
reverted PR - https://github.com/openedx/tubular/pull/562

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ruzniaievdm! I've created [OSPR-6642](https://openedx.atlassian.net/browse/OSPR-6642) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by ruzniaievdm** [comment]
@dianakhuangi I have added additional update kwargs for request
Hope this should solve the problem with unsupported media type url error
```
if 'headers' not in kwargs:
            kwargs['headers'] = {'Content-type': 'application/json'}
```

**Comment by natabene** [comment]
@ruzniaievdm Thank you for your contribution. @dianakhuang Will you review this or do you prefer that the owning team does?

**Comment by HassanJaveed84** [comment]
Thank you for this. 
We are going to test this, please hold off from merging this.

**Comment by dianakhuang** [comment]
It looks like there's something malformed in one of the calls, still. @HassanJaveed84 provided some error logs: https://gist.github.com/HassanJaveed84/7d39aebf39df440d8c19d6915b55e2c2

**Comment by ruzniaievdm** [comment]
@dianakhuang thanks, i will look into it

**Comment by ruzniaievdm** [comment]
@HassanJaveed84 Hi! The bug could not be reproduced locally, perhaps there is an approximate config file or variables that you should pay attention to?

**Comment by dianakhuang** [comment]
@HassanJaveed84 this should be ready for re-review.

**Comment by HassanJaveed84** [comment]
@dianakhuang this is good to merge.

**Review by dianakhuang — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@ruzniaievdm 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/tubular&entry.867055334=https://github.com/openedx/tubular/pull/564&entry.1484655318=https://github.com/ruzniaievdm&entry.752974735=2022-04-27+09:29&entry.1917517419=2022-06-24+12:58&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by HassanJaveed84** [comment]
@dianakhuang @ruzniaievdm getting 500 on various requests
```
03:03:36-0500 ERROR:tubular.edx_api:API Error: 500 Server Error: Internal Server Error for url: https://courses.edx.org/api/user/v1/accounts/retirement_partner_report_cleanup/ with status code: 500
03:03:36-0500 ERROR:backoff:Backing off retirement_partner_cleanup(...) for 0.6s (requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://courses.edx.org/api/user/v1/accounts/retirement_partner_report_cleanup/)
03:03:36-0500 INFO:tubular.edx_api:Trying again in 0.6 seconds after 1 tries calling <function LmsApi.retirement_partner_cleanup at 0x7f8c77cda310>
03:03:37-0500 ERROR:tubular.edx_api:API Error: 500 Server Error: Internal Server Error for url: https://courses.edx.org/api/user/v1/accounts/retirement_partner_report_cleanup/ with status code: 500
03:03:37-0500 ERROR:backoff:Backing off retirement_partner_cleanup(...) for 0.8s (requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://courses.edx.org/api/user/v1/accounts/retirement_partner_report_cleanup/)
03:03:37-0500 INFO:tubular.edx_api:Trying again in 0.8 seconds after 2 tries calling <function LmsApi.retirement_partner_cleanup at 0x7f8c77cda310>
03:03:38-0500 ERROR:tubular.edx_api:API Error: 500 Server Error: Internal Server Error for url: https://courses.edx.org/api/user/v1/accounts/retirement_partner_report_cleanup/ with status code: 500
03:03:38-0500 ERROR:backoff:Backing off retirement_partner_cleanup(...) for 0.5s (requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://courses.edx.org/api/user/v1/accounts/retirement_partner_report_cleanup/)
03:03:38-0500 INFO:tubular.edx_api:Trying again in 0.5 seconds after 3 tries calling <function LmsApi.retirement_partner_cleanup at 0x7f8c77cda310>
03:03:39-0500 ERROR:tubular.edx_api:API Error: 500 Server Error: Internal Server Error for url: https://courses.edx.org/api/user/v1/accounts/retirement_partner_report_cleanup/ with status code: 500
03:03:39-0500 ERROR:backoff:Backing off retirement_partner_cleanup(...) for 5.6s (requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://courses.edx.org/api/user/v1/accounts/retirement_partner_report_cleanup/)
03:03:39-0500 INFO:tubular.edx_api:Trying again in 5.6 seconds after 4 tries calling <function LmsApi.retirement_partner_cleanup at 0x7f8c77cda310>
03:03:44-0500 ERROR:tubular.edx_api:API Error: 500 Server Error: Internal Server Error for url: https://courses.edx.org/api/user/v1/accounts/retirement_partner_report_cleanup/ with status code: 500
03:03:44-0500 ERROR:backoff:Backing off retirement_partner_cleanup(...) for 12.8s (requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://courses.edx.org/api/user/v1/accounts/retirement_partner_report_cleanup/)
03:03:44-0500 INFO:tubular.edx_api:Trying again in 12.8 seconds after 5 tries calling <function LmsApi.retirement_partner_cleanup at 0x7f8c77cda310>
03:03:57-0500 ERROR:tubular.edx_api:API Error: 500 Server Error: Internal Server Error for url: https://courses.edx.org/api/user/v1/accounts/retirement_partner_report_cleanup/ with status code: 500
03:03:57-0500 ERROR:backoff:Backing off retirement_partner_cleanup(...) for 31.8s (requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://courses.edx.org/api/user/v1/accounts/retirement_partner_report_cleanup/)
03:03:57-0500 INFO:tubular.edx_api:Trying again in 31.8 seconds after 6 tries calling <function LmsApi.retirement_partner_cleanup at 0x7f8c77cda310>
03:04:29-0500 ERROR:tubular.edx_api:API Error: 500 Server Error: Internal Server Error for url: https://courses.edx.org/api/user/v1/accounts/retirement_partner_report_cleanup/ with status code: 500
03:04:29-0500 ERROR:backoff:Backing off retirement_partner_cleanup(...) for 28.0s (requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://courses.edx.org/api/user/v1/accounts/retirement_partner_report_cleanup/)
03:04:29-0500 INFO:tubular.edx_api:Trying again in 28.0 seconds after 7 tries calling <function LmsApi.retirement_partner_cleanup at 0x7f8c77cda310>
03:04:58-0500 ERROR:tubular.edx_api:API Error: 500 Server Error: Internal Server Error for url: https://courses.edx.org/api/user/v1/accounts/retirement_partner_report_cleanup/ with status code: 500
03:04:58-0500 ERROR:backoff:Backing off retirement_partner_cleanup(...) for 74.1s (requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://courses.edx.org/api/user/v1/accounts/retirement_partner_report_cleanup/)
03:04:58-0500 INFO:tubular.edx_api:Trying again in 74.1 seconds after 8 tries calling <function LmsApi.retirement_partner_cleanup at 0x7f8c77cda310>
03:06:12-0500 ERROR:tubular.edx_api:API Error: 500 Server Error: Internal Server Error for url: https://courses.edx.org/api/user/v1/accounts/retirement_partner_report_cleanup/ with status code: 500
03:06:12-0500 ERROR:backoff:Backing off retirement_partner_cleanup(...) for 196.3s (requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://courses.edx.org/api/user/v1/accounts/retirement_partner_report_cleanup/)
03:06:12-0500 INFO:tubular.edx_api:Trying again in 196.3 seconds after 9 tries calling <function LmsApi.retirement_partner_cleanup at 0x7f8c77cda310>
03:09:29-0500 ERROR:tubular.edx_api:API Error: 500 Server Error: Internal Server Error for url: https://courses.edx.org/api/user/v1/accounts/retirement_partner_report_cleanup/ with status code: 500
03:09:29-0500 ERROR:backoff:Backing off retirement_partner_cleanup(...) for 148.5s (requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://courses.edx.org/api/user/v1/accounts/retirement_partner_report_cleanup/)
03:09:29-0500 INFO:tubular.edx_api:Trying again in 148.5 seconds after 10 tries calling <function LmsApi.retirement_partner_cleanup at 0x7f8c77cda310>
03:11:57-0500 ERROR:tubular.edx_api:API Error: 500 Server Error: Internal Server Error for url: https://courses.edx.org/api/user/v1/accounts/retirement_partner_report_cleanup/ with status code: 500
03:11:57-0500 ERROR:backoff:Backing off retirement_partner_cleanup(...) for 98.8s (requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://courses.edx.org/api/user/v1/accounts/retirement_partner_report_cleanup/)
03:11:57-0500 INFO:tubular.edx_api:Trying again in 98.8 seconds after 11 tries calling <function LmsApi.retirement_partner_cleanup at 0x7f8c77cda310>
03:13:36-0500 ERROR:tubular.edx_api:API Error: 500 Server Error: Internal Server Error for url: https://courses.edx.org/api/user/v1/accounts/retirement_partner_report_cleanup/ with status code: 500
03:13:36-0500 ERROR:backoff:Giving up retirement_partner_cleanup(...) after 12 tries (requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://courses.edx.org/api/user/v1/accounts/retirement_partner_report_cleanup/)
03:13:36-0500 b'Partner report: Unexpected error occurred! Users may be stuck in the processing state!\n500 Server Error: Internal Server Error for url: https://courses.edx.org/api/user/v1/accounts/retirement_partner_report_cleanup/'
03:13:36-0500 b'Partner report: Traceback (most recent call last):\n  File "scripts/retirement_partner_report.py", line 396, in generate_report\n    config[\'LMS\'].retirement_partner_cleanup(all_usernames)\n  File "/var/lib/jenkins/workspace/retirement-partner-reporter/venv-51/lib/python3.8/site-packages/backoff/_sync.py", line 99, in retry\n    ret = target(*args, **kwargs)\n  File "/var/lib/jenkins/workspace/retirement-partner-reporter/venv-51/lib/python3.8/site-packages/backoff/_sync.py", line 99, in retry\n    ret = target(*args, **kwargs)\n  File "/var/lib/jenkins/workspace/retirement-partner-reporter/tubular/tubular/edx_api.py", line 344, in retirement_partner_cleanup\n    return self._request(\'POST\', api_url, json=data)\n  File "/var/lib/jenkins/workspace/retirement-partner-reporter/tubular/tubular/edx_api.py", line 63, in _request\n    response.raise_for_status()\n  File "/var/lib/jenkins/workspace/retirement-partner-reporter/venv-51/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: [https://courses.edx.org/api/user/v1/accounts/retirement_partner_report_cleanup/\n](https://courses.edx.org/api/user/v1/accounts/retirement_partner_report_cleanup//n)'

**Comment by dianakhuang** [comment]
@ruzniaievdm I am looking up the specific Traceback for this 500 in edx-platform to help with debugging.

**Comment by dianakhuang** [comment]
I believe this is the error log we'e seeing:
```
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/newrelic/hooks/framework_django.py", line 552, in wrapper
    return wrapped(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/newrelic/hooks/component_djangorestframework.py", line 61, in _nr_wrapper_APIView_dispatch_
    return wrapped(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/newrelic/hooks/component_djangorestframework.py", line 68, in _handle_exception_wrapper
    return wrapped(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/edx/app/edxapp/edx-platform/openedx/core/djangoapps/user_api/accounts/views.py", line 803, in retirement_partner_cleanup
    usernames = [u['original_username'] for u in request.data]
  File "/edx/app/edxapp/edx-platform/openedx/core/djangoapps/user_api/accounts/views.py", line 803, in <listcomp>
    usernames = [u['original_username'] for u in request.data]
TypeError: string indices must be integers
```

**Comment by dianakhuang** [comment]
I believe I have a fix here: https://github.com/openedx/tubular/pull/576 . @HassanJaveed84 when you get a chance, could you rerun the job on the new branch?

**Comment by ruzniaievdm** [comment]
@dianakhuang thank you very much for your traceback and I hope your fix will be correct.

@HassanJaveed84 could you tell me please the approximate structure of the json data sent in the `retirement_partner_cleanup` method for correct processing on the tubular side

**Pull request merged**
