### PR TITLE
FC-0001: Remove EdxRestApiClient usage in tubular

### PR DESCRIPTION
**Pull request by ruzniaievdm**
JIRA: [DEPR-138](https://openedx.atlassian.net/browse/DEPR-138)
https://github.com/openedx/public-engineering/issues/38
reverted PR - https://github.com/openedx/tubular/pull/558

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ruzniaievdm! I've created [OSPR-6640](https://openedx.atlassian.net/browse/OSPR-6640) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by dianakhuang — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@ruzniaievdm 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/tubular&entry.867055334=https://github.com/openedx/tubular/pull/562&entry.1484655318=https://github.com/ruzniaievdm&entry.752974735=2022-04-26+09:23&entry.1917517419=2022-04-26+17:33&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by dianakhuang** [comment]
We were getting this error when trying to run with these changes:
```
Client Error: Unsupported Media Type for url: https://courses.edx.org/api/user/v1/accounts/update_retirement_status/
```

**Comment by natabene** [comment]
@ruzniaievdm @dianakhuang Thank you both.

**Pull request merged**
