### PR TITLE
Allow HubspotAPI to send email to marketing upon successful deletion

### PR DESCRIPTION
**Pull request by bseverino**
### [MST-482](https://openedx.atlassian.net/browse/MST-482)

### CODE REVIEW

**Review by schenedx — APPROVED** [review]
👍

**Comment by pwnage101** [comment]
My only question is about whether the hubspot VID would be considered PII?

**Comment by bseverino** [comment]
@pwnage101 That's a good question, I'm not 100% sure. I'll see if I can find out.

**Review by tuchfarber — APPROVED** [review]

**Comment by bseverino** [comment]
@pwnage101 According to the Hubspot docs, anything using the VID requires authentication, so I don't think it would be considered PII: https://legacydocs.hubspot.com/docs/methods/contacts/get_contact

**Review by pwnage101 — APPROVED** [review]

**Pull request merged**
